from typing import Protocol

from tvagent.core.models import AudioClip, Fact, Person, PersonId, RenderState, Turn


class WakeWord(Protocol):
    def wait(self) -> None: ...

class AudioCapture(Protocol):
    def capture(self) -> AudioClip: ...

class SpeakerID(Protocol):
    def identify(self, clip: AudioClip) -> PersonId: ...
    def enroll(self, name: str, clip: AudioClip) -> Person: ...

class STT(Protocol):
    def transcribe(self, clip: AudioClip) -> str: ...

class LLM(Protocol):
    def respond(self, system: str, user: str, history: list[tuple[str, str]]) -> str: ...

class TTS(Protocol):
    def speak(self, text: str) -> None: ...

class MemoryStore(Protocol):
    def get_person(self, person_id: str) -> Person | None: ...
    def list_people(self) -> list[Person]: ...
    def upsert_person(self, person: Person) -> None: ...
    def save_turn(self, turn: Turn) -> None: ...
    def recent_turns(self, person_id: str, n: int) -> list[Turn]: ...
    def get_facts(self, person_id: str) -> list[Fact]: ...
    def add_fact(self, fact: Fact) -> None: ...

class Display(Protocol):
    def render(self, state: RenderState) -> None: ...
