from collections.abc import Iterator
from typing import Protocol

from tvagent.core.models import AudioClip, Fact, Person, PersonId, RenderState, Turn


class WakeWord(Protocol):
    def wait(self) -> None: ...


class AudioCapture(Protocol):
    def capture(self) -> AudioClip: ...


class SpeakerID(Protocol):
    def identify(self, clip: AudioClip) -> PersonId: ...
    def enroll(self, name: str, clips: list[AudioClip]) -> Person: ...


class STT(Protocol):
    def transcribe(self, clip: AudioClip) -> str: ...


class LLM(Protocol):
    def respond(self, system: str, user: str, history: list[tuple[str, str]]) -> str: ...
    def stream(self, system: str, user: str, history: list[tuple[str, str]]) -> Iterator[str]: ...


class TTS(Protocol):
    def speak(self, text: str) -> None: ...
    def synth(self, text: str) -> tuple[bytes, float]: ...  # (audio, duration seconds)
    def play(self, pcm: bytes) -> None: ...
    def stop(self) -> None: ...  # abort in-flight playback (barge-in)


class EchoCanceller(Protocol):
    """Subtracts the assistant's own playback (far-end) from the mic (near-end)
    so the barge-in detector doesn't hear the assistant's own voice."""

    def process(self, near: bytes, far: bytes) -> bytes: ...


class BargeInDetector(Protocol):
    """Watches the mic while the assistant is speaking so the user can talk over
    it. `arm` starts listening (before a reply), `speaking` is polled during the
    reply, `disarm` stops (after)."""

    def arm(self) -> None: ...
    def speaking(self) -> bool: ...
    def disarm(self) -> None: ...


class MemoryStore(Protocol):
    def get_person(self, person_id: str) -> Person | None: ...
    def list_people(self) -> list[Person]: ...
    def upsert_person(self, person: Person) -> None: ...
    def save_turn(self, turn: Turn) -> None: ...
    def recent_turns(self, person_id: str, n: int) -> list[Turn]: ...
    def get_facts(self, person_id: str) -> list[Fact]: ...
    def add_fact(self, fact: Fact) -> None: ...


class Display(Protocol):
    def render(self, state: RenderState) -> None: ...
